import axios from "axios";
import {
  ActiveWorkOrderSessionDTO,
  NotificationHistoryResponseDTO,
  NotificationMarkReadResponseDTO,
  WebPushSubscribeRequestDTO,
  WebPushUnsubscribeRequestDTO,
} from "@/types/notifications";

/**
 * Base URL for the Viking App Backend API.
 */
const BASE_URL = process.env.NEXT_PUBLIC_API_URL || "";
const STORAGE_KEY = "viking_active_work_order";

/**
 * Dedicated Axios Client for Public Client Endpoints.
 * Unlike the main apiClient, this instance does NOT intercept 401 errors
 * to redirect to the staff /login page. It allows public views to handle
 * validation failures cleanly and return to the public search form.
 */
const publicApiClient = axios.create({
  baseURL: BASE_URL,
  timeout: 15000,
  headers: {
    "Content-Type": "application/json",
  },
});

/**
 * Converts a Base64 URL-safe VAPID public key string into a Uint8Array<ArrayBuffer>
 * required by the browser's PushManager.subscribe() method.
 */
function urlBase64ToUint8Array(base64String: string): Uint8Array<ArrayBuffer> {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");
  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(new ArrayBuffer(rawData.length));
  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

/**
 * Public Notification Service:
 * Manages WebPush VAPID subscriptions, notification history retrieval,
 * morning sync rehydration storage, and Service Worker registration.
 */
export const publicNotificationService = {
  /**
   * Registers the Service Worker located in /sw.js safely on the client side.
   */
  registerServiceWorker: async (): Promise<ServiceWorkerRegistration | null> => {
    if (typeof window === "undefined" || !("serviceWorker" in navigator)) {
      return null;
    }
    try {
      const registration = await navigator.serviceWorker.register("/sw.js", {
        scope: "/",
      });
      return registration;
    } catch (error) {
      console.error("[SW-Register] Failed to register service worker:", error);
      return null;
    }
  },

  /**
   * Requests browser notification permission and subscribes the device using VAPID.
   * Sends the resulting subscription payload to the Go backend.
   */
  requestAndSubscribe: async (
    workOrderId: string,
    securityCode: string
  ): Promise<boolean> => {
    if (!workOrderId || !securityCode || securityCode === "undefined") {
      console.warn("[WebPush] Missing or invalid security code. Cannot subscribe to push alerts.");
      return false;
    }

    if (typeof window === "undefined" || !("serviceWorker" in navigator) || !("PushManager" in window)) {
      console.warn("[WebPush] Browser does not support WebPush notifications.");
      return false;
    }

    const vapidPublicKey = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;
    if (!vapidPublicKey) {
      console.error("[WebPush] NEXT_PUBLIC_VAPID_PUBLIC_KEY is missing from environment variables.");
      return false;
    }

    // 1. Request notification permission from the user
    const permission = await Notification.requestPermission();
    if (permission !== "granted") {
      console.warn("[WebPush] Notification permission was denied or dismissed by user.");
      return false;
    }

    // 2. Ensure Service Worker registration is ready
    const registration = await navigator.serviceWorker.ready;

    // 3. Subscribe with PushManager using the converted VAPID key
    const convertedVapidKey = urlBase64ToUint8Array(vapidPublicKey);
    let subscription = await registration.pushManager.getSubscription();

    if (!subscription) {
      subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: convertedVapidKey,
      });
    }

    const subJson = subscription.toJSON();
    if (!subJson.endpoint || !subJson.keys?.p256dh || !subJson.keys?.auth) {
      console.error("[WebPush] Invalid subscription structure generated by browser.");
      return false;
    }

    // 4. Send subscription to Go backend
    const payload: WebPushSubscribeRequestDTO = {
      workOrderId,
      securityCode,
      endpoint: subJson.endpoint,
      keys: {
        p256dh: subJson.keys.p256dh,
        auth: subJson.keys.auth,
      },
      userAgent: navigator.userAgent || "Unknown PWA Client",
    };

    await publicApiClient.post("/public/notifications/subscribe", payload);
    return true;
  },

  /**
   * Unsubscribes the current device from WebPush alerts and notifies backend.
   */
  unsubscribePush: async (): Promise<boolean> => {
    if (typeof window === "undefined" || !("serviceWorker" in navigator)) {
      return false;
    }

    const registration = await navigator.serviceWorker.ready;
    const subscription = await registration.pushManager.getSubscription();
    if (!subscription) {
      return true;
    }

    const endpoint = subscription.endpoint;
    await subscription.unsubscribe();

    const payload: WebPushUnsubscribeRequestDTO = { endpoint };
    try {
      await publicApiClient.post("/public/notifications/unsubscribe", payload);
    } catch (error) {
      console.warn("[WebPush] Backend unsubscribe call failed after local unbind:", error);
    }
    return true;
  },

  /**
   * Checks current browser permission and active push subscription state.
   */
  getSubscriptionState: async (): Promise<{ isSubscribed: boolean; permission: NotificationPermission }> => {
    if (typeof window === "undefined" || !("serviceWorker" in navigator) || !("PushManager" in window)) {
      return { isSubscribed: false, permission: "denied" };
    }
    const permission = Notification.permission;
    try {
      const registration = await navigator.serviceWorker.getRegistration();
      if (!registration) {
        return { isSubscribed: false, permission };
      }
      const subscription = await registration.pushManager.getSubscription();
      return { isSubscribed: !!subscription, permission };
    } catch {
      return { isSubscribed: false, permission };
    }
  },

  /**
   * Retrieves notification history for morning auto-sync and bell feed.
   */
  getHistory: async (workOrderId: string, securityCode: string): Promise<NotificationHistoryResponseDTO[]> => {
    if (!workOrderId || !securityCode || securityCode === "undefined") {
      return [];
    }
    const response = await publicApiClient.get<NotificationHistoryResponseDTO[]>(
      `/public/notifications/history?workOrderId=${encodeURIComponent(workOrderId)}&securityCode=${encodeURIComponent(securityCode)}`
    );
    return response.data;
  },

  /**
   * Marks all historical notifications as read to reset the bell badge counter.
   */
  markAsRead: async (workOrderId: string, securityCode: string): Promise<NotificationMarkReadResponseDTO> => {
    if (!workOrderId || !securityCode || securityCode === "undefined") {
      throw new Error("Invalid security code for marking notifications as read");
    }
    const response = await publicApiClient.post<NotificationMarkReadResponseDTO>(
      `/public/notifications/mark-read?workOrderId=${encodeURIComponent(workOrderId)}&securityCode=${encodeURIComponent(securityCode)}`
    );
    return response.data;
  },

  /**
   * Saves the active work order session to localStorage for morning rehydration.
   * Prevents storing sessions where securityCode is missing or literal 'undefined'.
   */
  saveActiveSession: (session: ActiveWorkOrderSessionDTO): void => {
    if (typeof window !== "undefined" && session.workOrderId && session.securityCode && session.securityCode !== "undefined") {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(session));
    }
  },

  /**
   * Retrieves the stored work order session from localStorage if present.
   * Automatically clears corrupted entries that lack a valid securityCode.
   */
  getActiveSession: (): ActiveWorkOrderSessionDTO | null => {
    if (typeof window === "undefined") {
      return null;
    }
    const stored = localStorage.getItem(STORAGE_KEY);
    if (!stored) return null;
    try {
      const parsed = JSON.parse(stored) as ActiveWorkOrderSessionDTO;
      if (!parsed.workOrderId || !parsed.securityCode || parsed.securityCode === "undefined") {
        localStorage.removeItem(STORAGE_KEY);
        return null;
      }
      return parsed;
    } catch {
      localStorage.removeItem(STORAGE_KEY);
      return null;
    }
  },

  /**
   * Clears the stored active session when exiting or switching orders.
   */
  clearActiveSession: (): void => {
    if (typeof window !== "undefined") {
      localStorage.removeItem(STORAGE_KEY);
    }
  },
};
