import { DiagnosticPointResponseDTO } from "./diagnostic";

/**
 * Valid state transitions for a Viking App Work Order.
 * IN_QUEUE represents the "En Espera" state seen in mobile UI.
 */
export type RepairStatus = "RECEIVED" | "IN_PROGRESS" | "IN_QUEUE" | "DONE" | "WITHDRAWN";

export interface WorkOrderResponseDTO {
  id: string;                 // UUID
  securityCode: string;       // WOVIK-XXXXX (Generated by backend upon creation)
  clientId: string;           // UUID
  clientDni?: number;         // int32
  clientName?: string;
  clientPhone?: string;
  deviceId: string;           // UUID
  deviceBrand?: string;
  deviceModel?: string;
  deviceSerialNumber?: string;
  staffId?: string;           // UUID
  staffName?: string;
  issueDescription: string;   // Min: 2, Max: 200 chars
  notes?: string;
  repairStatus: RepairStatus;
  createdAt: string;          // ISO-8601 Date-Time
  updatedAt?: string;
}

export interface WorkOrderCreateDTO {
  clientId: string;           // UUID
  deviceId: string;           // UUID
  issueDescription: string;
  notes?: string;
  repairStatus: RepairStatus;
}

/**
 * Supports partial PATCH updates as verified in Viking-App-Front types.
 * Allows reassigning hardware or client on the fly during workshop triage.
 */
export interface WorkOrderStatusUpdateDTO {
  repairStatus: RepairStatus;
  issueDescription?: string;
  clientId?: string;
  deviceId?: string;
}

export interface WorkOrderPublicQueryRequestDTO {
  id?: string;
  clientDni?: number;
  securityCode: string;
}

export interface WorkOrderPublicStatusResponseDTO {
  workOrder: WorkOrderResponseDTO;
  diagnosticPoints: DiagnosticPointResponseDTO[];
}
